# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_form.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_TestForm(object):
    def setupUi(self, TestForm):
        TestForm.setObjectName("TestForm")
        TestForm.resize(922, 474)
        self.horizontalLayout_7 = QtGui.QHBoxLayout(TestForm)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabs = QtGui.QTabWidget(TestForm)
        self.tabs.setObjectName("tabs")
        self.controls_tab = QtGui.QWidget()
        self.controls_tab.setObjectName("controls_tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.controls_tab)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.controls_tab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nav_buttons = NavigationWidget(self.controls_tab)
        self.nav_buttons.setMinimumSize(QtCore.QSize(128, 32))
        self.nav_buttons.setStyleSheet("#nav_buttons {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.nav_buttons.setObjectName("nav_buttons")
        self.horizontalLayout.addWidget(self.nav_buttons)
        self.breadcrumbs = BreadcrumbWidget(self.controls_tab)
        self.breadcrumbs.setMinimumSize(QtCore.QSize(0, 0))
        self.breadcrumbs.setStyleSheet("#breadcrumbs {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.breadcrumbs.setObjectName("breadcrumbs")
        self.horizontalLayout.addWidget(self.breadcrumbs)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.controls_tab)
        self.label_2.setMinimumSize(QtCore.QSize(200, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.elided_label = ElidedLabel(self.controls_tab)
        self.elided_label.setWordWrap(False)
        self.elided_label.setObjectName("elided_label")
        self.horizontalLayout_4.addWidget(self.elided_label)
        self.horizontalLayout_4.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtGui.QLabel(self.controls_tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search = SearchWidget(self.controls_tab)
        self.search.setMinimumSize(QtCore.QSize(128, 25))
        self.search.setStyleSheet("#search {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.search.setObjectName("search")
        self.horizontalLayout_2.addWidget(self.search)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_4 = QtGui.QLabel(self.controls_tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spinner_128x128 = SpinnerWidget(self.controls_tab)
        self.spinner_128x128.setMinimumSize(QtCore.QSize(128, 128))
        self.spinner_128x128.setMaximumSize(QtCore.QSize(128, 128))
        self.spinner_128x128.setStyleSheet("#spinner_128x128 {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.spinner_128x128.setObjectName("spinner_128x128")
        self.horizontalLayout_6.addWidget(self.spinner_128x128)
        self.spinner_64x64 = SpinnerWidget(self.controls_tab)
        self.spinner_64x64.setMinimumSize(QtCore.QSize(64, 64))
        self.spinner_64x64.setMaximumSize(QtCore.QSize(64, 64))
        self.spinner_64x64.setStyleSheet("#spinner_64x64 {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.spinner_64x64.setObjectName("spinner_64x64")
        self.horizontalLayout_6.addWidget(self.spinner_64x64)
        self.spinner_32x32 = SpinnerWidget(self.controls_tab)
        self.spinner_32x32.setMinimumSize(QtCore.QSize(32, 32))
        self.spinner_32x32.setMaximumSize(QtCore.QSize(32, 32))
        self.spinner_32x32.setStyleSheet("#spinner_32x32 {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.spinner_32x32.setObjectName("spinner_32x32")
        self.horizontalLayout_6.addWidget(self.spinner_32x32)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtGui.QSpacerItem(20, 94, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.tabs.addTab(self.controls_tab, "")
        self.overlays_tab = QtGui.QWidget()
        self.overlays_tab.setObjectName("overlays_tab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.overlays_tab)
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtGui.QLabel(self.overlays_tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.overlay_view = QtGui.QTreeView(self.overlays_tab)
        self.overlay_view.setObjectName("overlay_view")
        self.verticalLayout_3.addWidget(self.overlay_view)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtGui.QLabel(self.overlays_tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.sg_model_overlay_view = QtGui.QTreeView(self.overlays_tab)
        self.sg_model_overlay_view.setObjectName("sg_model_overlay_view")
        self.verticalLayout_4.addWidget(self.sg_model_overlay_view)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabs.addTab(self.overlays_tab, "")
        self.grouped_list_view_tab = QtGui.QWidget()
        self.grouped_list_view_tab.setObjectName("grouped_list_view_tab")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.grouped_list_view_tab)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.grouped_list_view = QtGui.QWidget(self.grouped_list_view_tab)
        self.grouped_list_view.setStyleSheet("#grouped_list_view {\n"
"background-color: rgb(255,255,255);\n"
"}")
        self.grouped_list_view.setObjectName("grouped_list_view")
        self.horizontalLayout_5.addWidget(self.grouped_list_view)
        self.tabs.addTab(self.grouped_list_view_tab, "")
        self.horizontalLayout_7.addWidget(self.tabs)

        self.retranslateUi(TestForm)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TestForm)

    def retranslateUi(self, TestForm):
        TestForm.setWindowTitle(QtGui.QApplication.translate("TestForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("TestForm", "Navigation Buttons and Breadcrumbs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("TestForm", "Elided Label:", None, QtGui.QApplication.UnicodeUTF8))
        self.elided_label.setText(QtGui.QApplication.translate("TestForm", "<html><head/><body><p><span style=\" font-size:large;\">this is an elided label </span>with a <span style=\" font-style:italic;\">really</span> long piece of <span style=\" font-weight:600;\">rich text that </span><span style=\" font-weight:600; font-style:italic;\">should</span><span style=\" font-weight:600;\"> behave correctly when elided!</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("TestForm", "Search:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("TestForm", "Spinners:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.controls_tab), QtGui.QApplication.translate("TestForm", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("TestForm", "Overlay Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("TestForm", "Shotgun Model Overlay Widget", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.overlays_tab), QtGui.QApplication.translate("TestForm", "Page", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs.setTabText(self.tabs.indexOf(self.grouped_list_view_tab), QtGui.QApplication.translate("TestForm", "Page", None, QtGui.QApplication.UnicodeUTF8))

from ..test_form import SearchWidget, NavigationWidget, BreadcrumbWidget, ElidedLabel, SpinnerWidget
